f=open('demo1.txt','w')
# g=f.read()
# print(g)
# print(f.readline())
f.write('i am vengence\n')
# f.close()
# print(f.read())
f1=open('hello.txt','r')
print(f1.read(7))
print(f1.tell())
# f1.write('helo bro\n')
# f1.write('do it now\n')
for i in f1:
    f.write(i)
